### ISSUE TITLE
ha_pair deployment (without bastion) systimaticaly fails with "Could not detect IP address for eth0" error

### ISSUE THREAD

**Issue by avistavkin** [Azure/sap-hana#225] opened 2019-09-17 19:32 UTC
Do my best to deploy ha_pair configuration and get systematically error "Could not detect IP address for eth0". 

Log and tfvars files are attached
[ha_pair_terraform.tfvars.txt](https://github.com/Azure/sap-hana/files/3623087/ha_pair_terraform.tfvars.txt)
[05 - ha_pair_Could_not_detect_IP_address_for_eth0.txt](https://github.com/Azure/sap-hana/files/3623092/05.-.ha_pair_Could_not_detect_IP_address_for_eth0.txt)

**Comment by rukawata** [comment] 2019-09-17 21:28
Hi,

I'm not able to reproduce the error you got.
If you try to deploy multiple times, do you always hit the same error?
If you try to deploy from a linux machine instead of cloud shell, will the deployment fail with the same error?

Also for the log, you could try to pipe the result into a file, then download it from the cloud shell: eg:
`terraform apply --auto-approve > 201909171428.log`

Thanks,
Nancy

**Comment by avistavkin** [comment] 2019-09-18 12:05
Thank you, Nancy! Great hit about > file.txt! 

I've tried one more time - same error here :( Even I took fresh tfvars from https://github.com/Azure/sap-hana. Log file is attached
[Could not detect IP address for eth0.txt](https://github.com/Azure/sap-hana/files/3626257/Could.not.detect.IP.address.for.eth0.txt)

**Comment by rukawata** [comment] 2019-09-19 16:40
Hi @avistavkin,

The error happens with command “ha-cluster-join -y -c 10.0.0.6 csync2”  
Since we can't reproduce the problem, we would need to check on your database servers where the deployment of HA cluster is happening. 
Could you share the logon information of the database servers with us (you can send me a direct email or whichever safe way you prefer)?

Thanks,
Nancy

**Comment by juandmi** [comment] 2019-11-27 21:24
Hi, I have the the same issue with the cluster join.
fatal: [ha1-hdb1]: FAILED! => {"changed": true, "cmd": "ha-cluster-join -y cluster", "delta": 
I'd like to try to deploy into another network. Can someone tell me where I can change the target NW?
Thanks,
Michael

**Comment by juandmi** [comment] 2019-11-28 08:41
Hi, I believe the issue is related to netmask if the network already exists in the subscription. When the netmask is different then the scripts expect. I was able to deploy by configuring other networks in a couple of files. Search for "10.0.0" [find . -type f -exec grep -H '10.0.0' {} \;] in the repository and configure your own different target networks and server IPs. This worked for me. 
Still it would be great to have the repository improved and be able to set target NW in terraform.tfvars. 
Regards,
Michael

**Comment by persiaAziz** [comment] 2020-01-28 20:32
A fix has been submitted: https://github.com/Azure/sap-hana/pull/272/files

**Comment by persiaAziz** [comment] 2020-02-06 01:09
fixed

**Closed by persiaAziz** 2020-02-06 01:09 UTC
