### ISSUE TITLE
[BUG] HA deployment (without Windows bastion host fails) during set-up-sbd-device : open_iscsi task

### ISSUE THREAD

**Issue by polichtm** [Azure/sap-hana#395] opened 2020-04-09 12:48 UTC
I'm seeing the following errors when performing an HA deployment (the corresponding terraform.tfvars below)

TASK [set-up-sbd-device : open_iscsi] ------------------------------------------------------**
fatal: [hn1-hdb0]: FAILED! => {"changed": false, "cmd": "/sbin/iscsiadm --mode node --targetname iqn.2006-04.cl1.local:cl1 --login --portal 10.0.0.17:3260", "msg": "iscsiadm: Could not login to [iface: default, target: iqn.2006-04.cl1.local:cl1, portal: 10.0.0.17,3260].\niscsiadm: initiator reported error (24 - iSCSI login failed due to authorization failure)\niscsiadm: Could not log into all portals\n", "rc": 24}
changed: [hn1-hdb1]

followed by

Error: Error running command '    OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES \
    AZURE_RESOURCE_GROUPS="hanav1ha-RG" \
    ANSIBLE_HOST_KEY_CHECKING="False" \
    ansible-playbook -u labuser \
    --private-key '~/.ssh/id_rsa' \
    --extra-vars="{ \"url_sapcar\": \"https://---------------------------.blob.core.windows.net/sapbits/SAPCAR_1311-80000935.EXE\", \
     \"url_hdbserver\": \"https://---------------------------.blob.core.windows.net/sapbits/IMDB_SERVER100_122_30-10009569.SAR\", \
     \"sap_sid\": \"HN1\", \
     \"sap_instancenum\": \"01\", \
     \"pwd_os_sapadm\": \"---------------------------\", \
     \"pwd_os_sidadm\": \"---------------------------\", \
     \"pwd_db_system\": \"---------------------------\", \
     \"pwd_hacluster\": \"---------------------------\", \
     \"hdb0_ip\": \"10.0.0.6\", \
     \"hdb1_ip\": \"10.0.0.7\", \
     \"use_hana2\": false, \
     \"hana1_db_mode\": \"single_container\", \
     \"lb_frontend_ip\": \"10.0.0.13\", \
     \"resource_group\": \"hanav1ha-RG\", \
     \"url_xsa_runtime\": \"\", \
     \"url_di_core\": \"\", \
     \"url_sapui5\": \"\", \
     \"url_portal_services\": \"\", \
     \"url_xs_services\": \"\", \
     \"url_shine_xsa\": \"\", \
     \"url_xsa_hrtt\": \"\", \
     \"url_xsa_webide\": \"\", \
     \"url_xsa_mta\": \"\", \
     \"url_sapcar_windows\": \"https://---------------------------.blob.core.windows.net/sapbits/SAPCAR_1311-80000938.EXE\", \
     \"url_hana_studio_windows\": \"https://---------------------------.blob.core.windows.net/sapbits/IMC_STUDIO2_122_30-80000323.SAR\", \
     \"url_timeout\": \"30\", \
     \"url_retries_cnt\": \"10\", \
     \"url_retries_delay\": \"10\",\
     \"package_retries_cnt\": \"10\", \
     \"package_retries_delay\": \"10\", \
     \"pwd_db_xsaadmin\": \"---------------------------\", \
     \"pw_bastion_windows\": \"---------------------------\", \
     \"bastion_username_windows\": \"bastion_user\", \
     \"pwd_db_tenant\": \"---------------------------\", \
     \"pwd_db_shine\": \"---------------------------\", \
     \"email_shine\": \"shine@emailaddress.com\", \
     \"install_xsa\": false, \
     \"install_shine\": false, \
     \"install_cockpit\": false, \
     \"install_webide\": false, \
     \"url_cockpit\": \"\" }" \
     -i '../../ansible/azure_rm.py' ../../ansible/ha_pair_playbook.yml
': exit status 2. Output:        "stdout_lines": [
            "Created Node ACL for iqn.2006-04.prod-cl1-0.local:prod-cl1-0",
            "Created mapped LUN 0."
        ]
    }
}

followed by 

NO MORE HOSTS LEFT ---------------------------------------------------------------------------------*

PLAY RECAP ---------------------------------------------------------------------------------*********
hanav1ha6117-iscsi         : ok=31   changed=16   unreachable=0    failed=0    skipped=2    rescued=0    ignored=0
hn1-hdb0                   : ok=29   changed=17   unreachable=0    failed=1    skipped=2    rescued=0    ignored=0
hn1-hdb1                   : ok=30   changed=18   unreachable=0    failed=0    skipped=2    rescued=0    ignored=0

Steps to reproduce
1) clone the repo
2) cd ~/sap-hana/deploy/vm/modules/ha_pair/
3) create terraform.tfvars with the following settings

az_region = "eastus"
az_resource_group = "hanav1ha-RG"
az_domain_name = "-------------"
vm_size = "Standard_E8s_v3"
sshkey_path_public = "~/.ssh/id_rsa.pub"
sshkey_path_private = "~/.ssh/id_rsa"
vm_user = "labuser"
sap_sid = "HN1"
sap_instancenum = "01"
url_sap_sapcar_linux = "https://---------------------------.blob.core.windows.net/sapbits/SAPCAR_1311-80000935.EXE"
url_sapcar_windows = "https://---------------------------.blob.core.windows.net/sapbits/SAPCAR_1311-80000938.EXE"
url_sap_hdbserver = "https://---------------------------.blob.core.windows.net/sapbits/IMDB_SERVER100_122_30-10009569.SAR"
url_hana_studio_windows = "https://---------------------------.blob.core.windows.net/sapbits/IMC_STUDIO2_122_30-80000323.SAR"
pw_os_sapadm = "---------------------------"
pw_os_sidadm = "---------------------------"
pw_db_system = "---------------------------"
pwd_db_xsaadmin = "---------------------------"
pwd_db_tenant = "---------------------------"
pwd_db_shine = "---------------------------"
email_shine = "shine@emailaddress.com"
useHana2 = false
install_xsa = false
install_shine = false
install_cockpit = false
install_webide = false
hdb_mdc = false
hana1_db_mode = "single_container"
windows_bastion = false
pw_bastion_windows = "---------------------------"
pw_hacluster = "---------------------------"

4) terraform init/plan/apply
rgds
Marcin

**Comment by polichtm** [comment] 2020-04-09 17:51
So it appears that the issue is caused by the invalid entry in /etc/iscsi/initiatorname.iscsi on both HANA HA nodes: 
iqn.2006-04.prod-cl1-x.local:prod-cl1-x
rather than 
iqn.2006-04.prod-cl1-0.local:prod-cl1-0
and 
iqn.2006-04.prod-cl1-1.local:prod-cl1-1
respectively
Pls advise how this can be remediated
rgds
Marcin

**Comment by rukawata** [comment] 2020-04-13 22:36
hi @polichtm, the reason you see x instead of 0/1 is because the hostname was not setup properly due to the same bug as #389. Because the code use azure_rm.py to pull the host information from Azure where we couldn't find host with host name `hn1-db0/hn1-db1` (not VM name), and only found `linux`.

We are working on possible fix to manually set the hostname to the correct one - `hn1-db0/hn1-db1`.
We will update you the progress on that.

**Comment by polichtm** [comment] 2020-04-14 00:59
Hi Nancy,
Appreciate the update – looking forward to the resolution.
Pls note that I’m also running into a different issue when including the Windows bastion host (as per #394)
Rgds
Marcin

**Comment by rukawata** [comment] 2020-04-15 18:11
Here is some update, after manually set hostname, we still faces an issue with ha-cluster-join which I'm working with SUSE on that.

Thanks,
Nancy

**Comment by polichtm** [comment] 2020-04-15 18:16
Hi Nancy - appreciated
rgds
Marcin

**Comment by rukawata** [comment] 2020-04-17 13:38
@polichtm, SUSE identified a bug with crm cluster join. They are working on a fix but may take weeks.
One way to get the fix early is to open a SUSE Support Service Request, so you can receive a PTF(PTF = Program Temporary Fix) with this fixed.
Or you can wait until v2 version finishes with HA (almost done with SLES, in progress with RHEL).

**Comment by polichtm** [comment] 2020-04-17 13:48
Hi Nancy,
Appreciated
What’s different about v2?
Rgds
Marcin

**Comment by rukawata** [comment] 2020-04-17 14:15
v2 is a refactored code with more flexibility in the deployment.
As for the HA clustering, in v2 we are using azure fencing agent instead of SBD device.

The code is under `sap-hana/deploy/v2` and will be moved up once we completely HA configuration.
At that time, the version you are using will be obsolete.

**Comment by polichtm** [comment] 2020-04-17 16:07
Hi Nancy,
This sounds reasonable. When do you anticipate v2 to become available?
Rgds
Marcin

**Comment by rukawata** [comment] 2020-04-17 16:57
@polichtm, our milestone to complete HA clustering for SLES should be done somewhere next week. I will give you an update when it's ready.

**Comment by rukawata** [comment] 2020-04-18 14:58
Hi @polichtm, we've applied a workaround for the SLES issue with cluster join. I will close this bug now.

**Closed by rukawata** 2020-04-18 14:58 UTC
Labels: bug

**Comment by rukawata** [comment] 2020-04-21 17:20
Hi @polichtm,
Our v2 is ready with SLES HA clustering.
For usage, you can refer to https://github.com/Azure/sap-hana/blob/master/deploy/v2/USAGE.md
For complete document, you can check https://github.com/Azure/sap-hana/blob/master/deploy/v2/README.MD

Hope that helps.

Thanks,
Nancy

**Comment by polichtm** [comment] 2020-04-22 01:31
Hi Nancy,
appreciated. 
Do you happen to know whether this also accounts for the issue referenced by #394 ?
thnx
Marcin

**Comment by rukawata** [comment] 2020-04-22 02:02
I do not think so by looking at the error. We will investigate the other issue and let you know.'

Thanks,
Nancy

**Comment by polichtm** [comment] 2020-04-22 02:03
thnx

**Comment by rukawata** [comment] 2020-04-22 21:54
@polichtm, we found further changed behavior with SLES HA clustering. Therefore we are fixing them in #446.

**Comment by polichtm** [comment] 2020-04-22 22:04
Appreciated…

**Comment by polichtm** [comment] 2020-04-26 01:23
Hi Nancy (@rukawata )
I'm apparently missing something - but it appears that v2 currently support only single instance (at least according to https://github.com/Azure/sap-hana/blob/master/deploy/v2/terraform/HANA.md) 
In the meantime, I'm still running into an issue with deployment using the existing ha code - here is the error message (same configuration as the one described originally):

TASK [host-name-resolution : Add hosts to /etc/hosts] **************************
fatal: [hn1-hdb1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_default_ipv4'\n\nThe error appears to be in '/home/marcin/sap-hana/deploy/vm/ansible/roles/host-name-resolution/tasks/main.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Add hosts to /etc/hosts\n  ^ here\n"}

Could you advise?
rgds
Marcin

**Comment by rukawata** [comment] 2020-04-27 15:44
Hi Marcin @polichtm,

The HA in v2 is currently in progress for the RHEL clustering, therefore in the document it is not showed as available.

The error you see is probably caused by some transient issue caused by SLES image. Have you tried to deploy again see if you could reproduce that?

Thanks,
Nancy

**Comment by polichtm** [comment] 2020-04-27 15:47
Hi Nancy @rukawata 
I tried 2 times - with the same outcome...
rgds
Marcin

**Comment by rukawata** [comment] 2020-04-27 15:52
Hi Marcin @polichtm,

Did you delete the resource group completely before you retry? Those issue persists once the VM is deployed.

Thanks,
Nancy

**Comment by polichtm** [comment] 2020-04-27 15:55
Correct - I always delete the resource group and the local clone of the repo
rgds
Marcin

**Comment by rukawata** [comment] 2020-04-27 15:59
Hi Marcin @polichtm,
I can't reproduce your issue with the template you provided earlier. Can you try to deploy in a different region?

Thanks,
Nancy

**Comment by polichtm** [comment] 2020-04-27 16:02
Hi Nancy,
I can try deploying into the region you were using - which one worked for you?
rgds
Marcin

**Comment by rukawata** [comment] 2020-04-27 16:59
Hi Marcin @polichtm,

My tests are done in westus2.
Please also move your SAP downloads to the same region because I noticed that cross region downloads may be flaky and slow.

Thanks,
Nancy

**Comment by polichtm** [comment] 2020-04-27 17:03
certainly - will give it a try
thnx
Marcin

**Comment by polichtm** [comment] 2020-05-01 01:11
Hi Nancy @rukawata 
works without any issues in westus2...
appreciate all the help with this
thnx
Marcin
